apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data: # access for a user that is not the creator of the cluster
  mapUsers: |
    - userarn: arn:aws:iam::434817990501:user/github-ci
      username: github-ci
      groups:
        - system:masters
